../../../rtl/core/alu_blocks/cla32_cla4.v
../../../rtl/core/alu_blocks/adder_cla32.v
../../../rtl/core/alu_blocks/adder.v
../../../rtl/core/alu_blocks/comparator.v
../../../rtl/core/alu.v
../../../rtl/core/branch_comparator.v
../../../rtl/core/control_unit.v
../../../rtl/core/immediate_generator.v
../../../rtl/core/jump_target_generator.v
../../../rtl/core/pc_control.v
../../../rtl/core/register_file.v
../../../rtl/memory/bram_rom.v
../../../rtl/memory/bram_be.v
../../../rtl/memory/instruction_memory.v
../../../rtl/memory/data_memory.v
../../../rtl/core/instruction_splitter.v
../../../rtl/core/mips_single_cycle_top.v
../../../testbench/tb_top/tb_mips_single_cycle_top_smoke.v
